import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav/NavBar";
import BurgerMenu from "@/components/burgerMenu/BurgerMenu";
import SplashCursor from "@/components/splashCursor/SplashCursor";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SplashCursor />
        <NavBar />
        <BurgerMenu />
        {children}
      </body>
    </html>
  );
}
